/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    doctors: DoctorAuthOperations;
    organisations: OrganisationAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    doctors: Doctor;
    organisations: Organisation;
    media: Media;
    'doctor-categories': DoctorCategory;
    appointments: Appointment;
    messages: Message;
    'call-recordings': CallRecording;
    feedbacks: Feedback;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    doctors: DoctorsSelect<false> | DoctorsSelect<true>;
    organisations: OrganisationsSelect<false> | OrganisationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'doctor-categories': DoctorCategoriesSelect<false> | DoctorCategoriesSelect<true>;
    appointments: AppointmentsSelect<false> | AppointmentsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    'call-recordings': CallRecordingsSelect<false> | CallRecordingsSelect<true>;
    feedbacks: FeedbacksSelect<false> | FeedbacksSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User | Doctor | Organisation;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface DoctorAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface OrganisationAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'user' | 'admin';
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors".
 */
export interface Doctor {
  id: number;
  name?: string | null;
  organisation: number | Organisation;
  categories?: (number | DoctorCategory)[] | null;
  experience?: number | null;
  /**
   * Например: Врач высшей категории, Кандидат медицинских наук
   */
  degree?: string | null;
  price?: number | null;
  photo?: (number | null) | Media;
  bio?: string | null;
  education?:
    | {
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  services?:
    | {
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Длительность одной консультации
   */
  slotDuration?: ('15' | '30' | '45' | '60' | '90') | null;
  /**
   * Расписание на конкретные даты. Можно ставить на год вперед.
   */
  schedule?:
    | {
        /**
         * Формат YYYY-MM-DD
         */
        date: string;
        slots?:
          | {
              /**
               * Формат HH:MM, например 09:00
               */
              time: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'doctors';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organisations".
 */
export interface Organisation {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'organisations';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctor-categories".
 */
export interface DoctorCategory {
  id: number;
  name: string;
  /**
   * Уникальный идентификатор для URL (например: therapist)
   */
  slug: string;
  description?: string | null;
  /**
   * Название иконки из библиотеки Lucide (например: stethoscope, heart, brain)
   */
  icon?: string | null;
  /**
   * Загрузите собственное изображение иконки (PNG/SVG/JPG)
   */
  iconImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments".
 */
export interface Appointment {
  id: number;
  doctor: number | Doctor;
  user: number | User;
  /**
   * Заполняется автоматически для удобного отображения
   */
  doctorName?: string | null;
  /**
   * Заполняется автоматически
   */
  userName?: string | null;
  specialty?: string | null;
  /**
   * Формат YYYY-MM-DD
   */
  date: string;
  /**
   * Формат HH:MM
   */
  time: string;
  price?: number | null;
  status: 'confirmed' | 'in_progress' | 'completed' | 'cancelled';
  /**
   * Предпочтительный способ связи пациента
   */
  connectionType?: ('chat' | 'audio' | 'video') | null;
  /**
   * Если включено, пациент не может отправлять сообщения
   */
  chatBlocked?: boolean | null;
  /**
   * Видеозапись видеоконсультации (если проводилась)
   */
  recording?: (number | null) | Media;
  /**
   * Состояние текущего видеозвонка для поддержки переподключения
   */
  activeCall?: {
    isActive?: boolean | null;
    startedAt?: string | null;
    doctorPeerId?: string | null;
    userPeerId?: string | null;
    doctorConnected?: boolean | null;
    userConnected?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  appointment: number | Appointment;
  /**
   * Полиморфная связь: может быть пользователем или врачом. Для системных сообщений = null
   */
  sender?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'doctors';
        value: number | Doctor;
      } | null);
  /**
   * Если включено, сообщение отображается как системное уведомление
   */
  isSystemMessage?: boolean | null;
  text?: string | null;
  attachment?: (number | null) | Media;
  read?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "call-recordings".
 */
export interface CallRecording {
  id: number;
  appointment: number | Appointment;
  doctor: number | Doctor;
  recordingType?: ('video' | 'audio') | null;
  video: number | Media;
  durationSeconds?: number | null;
  recordedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedbacks".
 */
export interface Feedback {
  id: number;
  /**
   * Пользователь, оставивший отзыв
   */
  user: number | User;
  /**
   * Врач, которому оставлен отзыв
   */
  doctor: number | Doctor;
  /**
   * Консультация, по которой оставлен отзыв
   */
  appointment: number | Appointment;
  /**
   * Оценка от 1 до 5 звёзд
   */
  rating: number;
  /**
   * Текст отзыва пациента
   */
  text?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'doctors';
        value: number | Doctor;
      } | null)
    | ({
        relationTo: 'organisations';
        value: number | Organisation;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'doctor-categories';
        value: number | DoctorCategory;
      } | null)
    | ({
        relationTo: 'appointments';
        value: number | Appointment;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'call-recordings';
        value: number | CallRecording;
      } | null)
    | ({
        relationTo: 'feedbacks';
        value: number | Feedback;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'doctors';
        value: number | Doctor;
      }
    | {
        relationTo: 'organisations';
        value: number | Organisation;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'doctors';
        value: number | Doctor;
      }
    | {
        relationTo: 'organisations';
        value: number | Organisation;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors_select".
 */
export interface DoctorsSelect<T extends boolean = true> {
  name?: T;
  organisation?: T;
  categories?: T;
  experience?: T;
  degree?: T;
  price?: T;
  photo?: T;
  bio?: T;
  education?:
    | T
    | {
        value?: T;
        id?: T;
      };
  services?:
    | T
    | {
        value?: T;
        id?: T;
      };
  slotDuration?: T;
  schedule?:
    | T
    | {
        date?: T;
        slots?:
          | T
          | {
              time?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organisations_select".
 */
export interface OrganisationsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctor-categories_select".
 */
export interface DoctorCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  iconImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments_select".
 */
export interface AppointmentsSelect<T extends boolean = true> {
  doctor?: T;
  user?: T;
  doctorName?: T;
  userName?: T;
  specialty?: T;
  date?: T;
  time?: T;
  price?: T;
  status?: T;
  connectionType?: T;
  chatBlocked?: T;
  recording?: T;
  activeCall?:
    | T
    | {
        isActive?: T;
        startedAt?: T;
        doctorPeerId?: T;
        userPeerId?: T;
        doctorConnected?: T;
        userConnected?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  appointment?: T;
  sender?: T;
  isSystemMessage?: T;
  text?: T;
  attachment?: T;
  read?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "call-recordings_select".
 */
export interface CallRecordingsSelect<T extends boolean = true> {
  appointment?: T;
  doctor?: T;
  recordingType?: T;
  video?: T;
  durationSeconds?: T;
  recordedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedbacks_select".
 */
export interface FeedbacksSelect<T extends boolean = true> {
  user?: T;
  doctor?: T;
  appointment?: T;
  rating?: T;
  text?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  heroTitle: string;
  heroSubtitle?: string | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}